services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Tag\:
    resource: '../Classes/*'

  B13\Tag\Controller\SuggestReceiver:
    public: true

  B13\Tag\Persistence\PrepareTagItems:
    public: true
